# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 16:26
from __future__ import unicode_literals

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170817_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', null=True, upload_to=''),
        ),
    ]
